### ISSUE TITLE
Transactions from a smart contract

### ISSUE THREAD

**Issue by Massendefekt** [Lamden/contracting#287]
Hi there.

I've read through your documentation but couldn't find any specifics on how to accept payments to a smart contract / make transactions from a smart contract. Is this even possible?

If it is possible and just not documented, I'm happy to help out with the documentation of this.

Thanks four your time :D

**Comment by Endogen** [comment]
What exactly do you want to transfer, TAU?
```python
@export
def fund_contract(amount: float):
    importlib.import_module('currency').transfer_from(
        main_account=ctx.caller,
        amount=amount,
        to=ctx.this)
```
That will send the `amount` of TAU to the smart contract if the user executes it. On the other hand, if the user wants to make a normal transaction and send TAU to a specific contract, just use the contract name in the `TO` field of the transaction.

@StuartFarmer can this be closed?

**Comment by Massendefekt** [comment]
Back then I ended up with a similar solution, thanks anyway :)
