### ISSUE TITLE
SUP-0003 - Parallelism

### ISSUE THREAD

**Issue by StuartFarmer** [Lamden/contracting#7]
# SUP-0003
## Parallelism

Smart contracts are at this point in time not parallel. We need to decide how to change that. I have several thoughts.

If you know all the data that is going to be accessed beforehand, you could introduce concurrency by analyzing queries for conflicts and putting those in similar blocks.

To do this, you could have all of the queries exist in a separate function from the logic and analyze that function before running the logic and the writes.

```
def transfer(to, from, amount):
    def queries():
        to_balance = balances.select().where('address' == to).run()
        from_balance = balances.select().where('address' == from).run()
        return {'to' : to_balance, 'from' : from_balance}
    def logic():
        to_ = queries['to']
        from_ = queries['from']
        if from_['balance'] >= amount:
            ...
```

I'm thinking that it would also be helpful for every row to have a hash that serves as its primary index. This would allow us to keep track of the rows we are going to use very easily before we batch / order them into blocks. The database would be some sort of KV / SQL hybrid in that case.

This isn't really very graceful however. It interferes with the natural development process and requires you to know what data you are going to access before you write the logic to the contract. This is unknown a lot of time during experimentation.

**Comment by JeffWScott** [comment]
@StuartFarmer Primary index hash is a great idea

**Comment by StuartFarmer** [comment]
Exploring other databases such as https://www.arangodb.com/ might be interesting too. This is a hybrid database that uses RocksDB for storage like us but supports several query types. It's NoSQL under the hood, but you can do SQL type queries without a problem.

However, it's a proprietary query language so we'd give up the SQL standard.
